name: Delete DNS Auto-Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Workflow Title"
        required: true
        default: "Delete DNS Auto-Update"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete DNS Auto-Update
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: 'DNS Auto-Update'
      - name: Delete Self
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: 'Delete DNS Auto-Update'
