name: Delete All Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨12点自动运行
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Workflow Title"
        required: true
        default: "Delete All Workflow Runs"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete All Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}  # 使用 GitHub 提供的令牌
          repository: ${{ github.repository }}
          retain_days: 0               # 保留0天
          keep_minimum_runs: 0         # 不保留任何记录
          delete_workflow_pattern: DNS Auto-Update 

      - name: Delete Self
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}  # 使用 GitHub 提供的令牌
          repository: ${{ github.repository }}
          retain_days: 1               # 保留1天
          keep_minimum_runs: 1         # 保留至少1个运行
          delete_workflow_pattern: Delete All Workflow Runs
