name: DNS Auto-Update

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  update-dns:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # 如果使用子模块

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run DNS Updater (IPv4)
      env:
        KEY: ${{ secrets.KEY }}
        DOMAINS: ${{ secrets.DOMAINS }}
        SECRETID: ${{ secrets.SECRETID }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
        DNS_SERVER: "3.1"      # 华为云示例
        TTL: "300"
      run: |
        python dns_updater.py A

    - name: Run DNS Updater (IPv6)
      if: always()  # 可选是否运行
      env:
        KEY: ${{ secrets.KEY }}
        DOMAINS: ${{ secrets.DOMAINS }}
        SECRETID: ${{ secrets.SECRETID }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
        DNS_SERVER: "3.1"      # 华为云示例
        TTL: "300"
      run: |
        python dns_updater.py AAAA
